# Copyright (C) 2020 The MoKee Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/meizu/m1882/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/meizu/m1882

PRODUCT_COPY_FILES += \
    vendor/meizu/m1882/proprietary/vendor/firmware/aw_165hz.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_165hz.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/aw_166hz.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_166hz.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/aw_167hz.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_167hz.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/aw_168hz.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_168hz.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/aw_169hz.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_169hz.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/aw_170hz.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_170hz.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/aw_171hz.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_171hz.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/aw_172hz.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_172hz.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/aw_173hz.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_173hz.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/aw_174hz.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_174hz.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/aw_175hz.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_175hz.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/cleanup_ring.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cleanup_ring.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/coin_ring.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/coin_ring.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/defalm_ring.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/defalm_ring.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/defsim_ring.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/defsim_ring.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/mpacc_ring.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mpacc_ring.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/plug_usb_ring.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/plug_usb_ring.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sim_ring00.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring00.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sim_ring01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring01.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sim_ring02.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring02.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sim_ring03.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring03.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sim_ring04.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring04.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sim_ring05.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring05.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sim_ring06.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring06.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sim_ring07.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring07.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sim_ring08.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring08.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sim_ring09.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring09.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sim_ring10.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring10.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sim_ring11.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring11.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sim_ring12.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring12.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sim_ring13.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring13.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sim_ring14.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring14.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sim_ring15.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring15.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sim_ring16.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring16.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sim_ring17.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring17.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sim_ring18.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring18.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sim_ring19.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring19.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sim_ring20.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring20.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sim_ring21.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring21.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sim_ring22.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring22.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sim_ring23.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring23.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sim_ring24.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring24.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sim_ring25.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring25.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sim_ring26.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring26.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sim_ring27.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring27.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sim_ring28.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring28.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sim_ring29.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring29.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sim_ring30.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring30.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sim_ring31.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring31.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sim_ring32.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring32.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sim_ring33.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring33.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sim_ring34.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring34.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sim_ring35.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring35.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sim_ring36.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring36.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sim_ring37.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring37.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sim_ring38.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring38.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sim_ring39.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring39.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sim_ring40.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring40.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sms_ring01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring01.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sms_ring02.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring02.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sms_ring03.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring03.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sms_ring04.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring04.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sms_ring05.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring05.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sms_ring06.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring06.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sms_ring07.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring07.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sms_ring08.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring08.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sms_ring09.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring09.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sms_ring10.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring10.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sms_ring11.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring11.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sms_ring12.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring12.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sms_ring13.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring13.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sms_ring14.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring14.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sms_ring15.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring15.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sms_ring16.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring16.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sms_ring17.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring17.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sms_ring18.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring18.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sms_ring19.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring19.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sms_ring20.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring20.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sms_ring21.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring21.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sms_ring22.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring22.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sms_ring23.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring23.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sms_ring24.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring24.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sms_ring25.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring25.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sms_ring26.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring26.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sms_ring27.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring27.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sms_ring28.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring28.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sms_ring29.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring29.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sms_ring30.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring30.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sms_ring31.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring31.bin \
    vendor/meizu/m1882/proprietary/vendor/firmware/sms_ring32.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring32.bin \
    vendor/meizu/m1882/proprietary/vendor/lib/modules/llcc_perfmon.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/llcc_perfmon.ko \
    vendor/meizu/m1882/proprietary/vendor/lib/modules/modules.alias:$(TARGET_COPY_OUT_VENDOR)/lib/modules/modules.alias \
    vendor/meizu/m1882/proprietary/vendor/lib/modules/modules.dep:$(TARGET_COPY_OUT_VENDOR)/lib/modules/modules.dep \
    vendor/meizu/m1882/proprietary/vendor/lib/modules/mpq-adapter.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/mpq-adapter.ko \
    vendor/meizu/m1882/proprietary/vendor/lib/modules/mpq-dmx-hw-plugin.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/mpq-dmx-hw-plugin.ko \
    vendor/meizu/m1882/proprietary/vendor/lib/modules/pinctrl-wcd.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/pinctrl-wcd.ko \
    vendor/meizu/m1882/proprietary/vendor/lib/modules/qca_cld3_wlan.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/qca_cld3_wlan.ko \
    vendor/meizu/m1882/proprietary/vendor/lib/modules/rdbg.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/rdbg.ko \
    vendor/meizu/m1882/proprietary/vendor/lib/modules/snd-soc-cs35l41-spi.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/snd-soc-cs35l41-spi.ko \
    vendor/meizu/m1882/proprietary/vendor/lib/modules/snd-soc-cs35l41.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/snd-soc-cs35l41.ko \
    vendor/meizu/m1882/proprietary/vendor/lib/modules/snd-soc-sdm845.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/snd-soc-sdm845.ko \
    vendor/meizu/m1882/proprietary/vendor/lib/modules/snd-soc-wcd-mbhc.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/snd-soc-wcd-mbhc.ko \
    vendor/meizu/m1882/proprietary/vendor/lib/modules/snd-soc-wcd-spi.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/snd-soc-wcd-spi.ko \
    vendor/meizu/m1882/proprietary/vendor/lib/modules/snd-soc-wcd934x.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/snd-soc-wcd934x.ko \
    vendor/meizu/m1882/proprietary/vendor/lib/modules/snd-soc-wcd9xxx.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/snd-soc-wcd9xxx.ko \
    vendor/meizu/m1882/proprietary/vendor/lib/modules/swr-wcd-ctrl.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/swr-wcd-ctrl.ko \
    vendor/meizu/m1882/proprietary/vendor/lib/modules/tspp.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/tspp.ko \
    vendor/meizu/m1882/proprietary/vendor/lib/modules/wcd-core.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/wcd-core.ko \
    vendor/meizu/m1882/proprietary/vendor/lib/modules/wcd-dsp-glink.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/wcd-dsp-glink.ko
